# Generated by Django 4.0 on 2021-12-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
