# Generated by Django 4.0 on 2021-12-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagesList',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
